//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Java.Interop.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Java.Interop.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: method &apos;{0}&apos; in type &apos;{1}&apos; has unnamed parameters..
        /// </summary>
        public static string ApiXmlAdjuster_0001 {
            get {
                return ResourceManager.GetString("ApiXmlAdjuster_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: &apos;{0}&apos; is referenced as base type of &apos;{1}&apos; and expected to have generic type parameters, but it does not..
        /// </summary>
        public static string ApiXmlAdjuster_0002 {
            get {
                return ResourceManager.GetString("ApiXmlAdjuster_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while processing Java class &apos;{0}&apos;: {1}..
        /// </summary>
        public static string ApiXmlAdjuster_0003 {
            get {
                return ResourceManager.GetString("ApiXmlAdjuster_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while processing Java interface &apos;{0}&apos;: {1}..
        /// </summary>
        public static string ApiXmlAdjuster_0004 {
            get {
                return ResourceManager.GetString("ApiXmlAdjuster_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while resolving &apos;{0}&apos; in &apos;{1}&apos;: {2}..
        /// </summary>
        public static string ApiXmlAdjuster_0005 {
            get {
                return ResourceManager.GetString("ApiXmlAdjuster_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: failed to resolve generic constraint: &apos;{0}&apos;: {1}..
        /// </summary>
        public static string ApiXmlAdjuster_0006 {
            get {
                return ResourceManager.GetString("ApiXmlAdjuster_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For &apos;{0}.{1}&apos;, referenced generic arguments count does not match the base type parameters definition..
        /// </summary>
        public static string ApiXmlAdjuster_0007 {
            get {
                return ResourceManager.GetString("ApiXmlAdjuster_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; was not found..
        /// </summary>
        public static string ApiXmlAdjuster_0008 {
            get {
                return ResourceManager.GetString("ApiXmlAdjuster_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: XmlReader should be positioned on attribute, but it is on &apos;{0}&apos;..
        /// </summary>
        public static string ApiXmlAdjuster_0009 {
            get {
                return ResourceManager.GetString("ApiXmlAdjuster_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Element &apos;{1}&apos; requires attribute &apos;{2}&apos;..
        /// </summary>
        public static string ApiXmlAdjuster_0010 {
            get {
                return ResourceManager.GetString("ApiXmlAdjuster_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: EndElement of &apos;{1}&apos; was expected, but is type &apos;{2}&apos; with name &apos;{3}&apos; instead..
        /// </summary>
        public static string ApiXmlAdjuster_0011 {
            get {
                return ResourceManager.GetString("ApiXmlAdjuster_0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Unexpected element or content in &apos;{1}&apos;: node is &apos;{2}&apos;, name is &apos;{3}&apos;. Allowed elements are: &apos;{4}&apos;..
        /// </summary>
        public static string ApiXmlAdjuster_0012 {
            get {
                return ResourceManager.GetString("ApiXmlAdjuster_0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Element &apos;{1}&apos; has an unexpected attribute: &apos;{2}&apos;. Allowed attributes are: &apos;{3}&apos;..
        /// </summary>
        public static string ApiXmlAdjuster_0013 {
            get {
                return ResourceManager.GetString("ApiXmlAdjuster_0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load .jar entry &apos;{0}&apos;: {1}..
        /// </summary>
        public static string Bytecode_0001 {
            get {
                return ResourceManager.GetString("Bytecode_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation file not found: &apos;{0}&apos;..
        /// </summary>
        public static string Bytecode_0002 {
            get {
                return ResourceManager.GetString("Bytecode_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to match expression &apos;{0}&apos;, expected {1} parameter(s) but got {2} parameter(s)..
        /// </summary>
        public static string Bytecode_0003 {
            get {
                return ResourceManager.GetString("Bytecode_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter match for &apos;{0}.{1}&apos;. (expression: &apos;{2}&apos;).
        /// </summary>
        public static string Bytecode_0004 {
            get {
                return ResourceManager.GetString("Bytecode_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse Kotlin metadata on &apos;{0}&apos;: {1}..
        /// </summary>
        public static string Bytecode_0005 {
            get {
                return ResourceManager.GetString("Bytecode_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differing number of &apos;throws&apos; declarations on &apos;{0}{1}&apos;..
        /// </summary>
        public static string Bytecode_0006 {
            get {
                return ResourceManager.GetString("Bytecode_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get parameter names for &apos;{0}.{1}&apos;: {2}..
        /// </summary>
        public static string Bytecode_0007 {
            get {
                return ResourceManager.GetString("Bytecode_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse annotation XML file: {0}..
        /// </summary>
        public static string Bytecode_0008 {
            get {
                return ResourceManager.GetString("Bytecode_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove old constants: {0}..
        /// </summary>
        public static string Generator_BG4000 {
            get {
                return ResourceManager.GetString("Generator_BG4000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process enum mapping. Text line: {0}..
        /// </summary>
        public static string Generator_BG4100 {
            get {
                return ResourceManager.GetString("Generator_BG4100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during processing metadata fixup: {0}..
        /// </summary>
        public static string Generator_BG4200 {
            get {
                return ResourceManager.GetString("Generator_BG4200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XPath specification: {0}..
        /// </summary>
        public static string Generator_BG4300 {
            get {
                return ResourceManager.GetString("Generator_BG4300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target attribute name is not specified for path: {0}..
        /// </summary>
        public static string Generator_BG4307 {
            get {
                return ResourceManager.GetString("Generator_BG4307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected &apos;global::&apos; specification. This error happens if &apos;global::&apos; is specified in the Metadata.xml transform file, for example..
        /// </summary>
        public static string Generator_BG4400 {
            get {
                return ResourceManager.GetString("Generator_BG4400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;lang-features=default-interface-methods&apos; is not compatible with &apos;codegen-target=xamarinandroid&apos;..
        /// </summary>
        public static string Generator_BG4500 {
            get {
                return ResourceManager.GetString("Generator_BG4500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected class child {0}..
        /// </summary>
        public static string Generator_BG8101 {
            get {
                return ResourceManager.GetString("Generator_BG8101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; has unknown base type &apos;{1}&apos;..
        /// </summary>
        public static string Generator_BG8102 {
            get {
                return ResourceManager.GetString("Generator_BG8102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; has invalid base type &apos;{1}&apos;..
        /// </summary>
        public static string Generator_BG8103 {
            get {
                return ResourceManager.GetString("Generator_BG8103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse assembly &apos;{0}&apos;: {1}..
        /// </summary>
        public static string Generator_BG8200 {
            get {
                return ResourceManager.GetString("Generator_BG8200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For constructor &apos;{0}&apos;, could not find enclosing type &apos;{1}&apos;..
        /// </summary>
        public static string Generator_BG8300 {
            get {
                return ResourceManager.GetString("Generator_BG8300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected field type `{0}` ({1})..
        /// </summary>
        public static string Generator_BG8400 {
            get {
                return ResourceManager.GetString("Generator_BG8400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping &apos;{0}.{1}&apos; due to a duplicate method name. (Java type: &apos;{2}&apos;).
        /// </summary>
        public static string Generator_BG8401_Method {
            get {
                return ResourceManager.GetString("Generator_BG8401_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping &apos;{0}.{1}&apos; due to a duplicate nested type name. (Java type: &apos;{2}&apos;).
        /// </summary>
        public static string Generator_BG8401_NestedType {
            get {
                return ResourceManager.GetString("Generator_BG8401_NestedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping &apos;{0}.{1}&apos; due to a duplicate field or property name. (Java type: &apos;{2}&apos;).
        /// </summary>
        public static string Generator_BG8401_Property {
            get {
                return ResourceManager.GetString("Generator_BG8401_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping &apos;{0}.{1}&apos; due to a duplicate field. (Java type: &apos;{2}&apos;).
        /// </summary>
        public static string Generator_BG8402 {
            get {
                return ResourceManager.GetString("Generator_BG8402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected child element of &apos;&lt;interface&gt;&apos;: &apos;{0}&apos;..
        /// </summary>
        public static string Generator_BG8500 {
            get {
                return ResourceManager.GetString("Generator_BG8500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No event name provided in &apos;{0}.{1}&apos;..
        /// </summary>
        public static string Generator_BG8501 {
            get {
                return ResourceManager.GetString("Generator_BG8501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidating &apos;{0}&apos; and all its nested types because some of its interfaces were invalid..
        /// </summary>
        public static string Generator_BG8502 {
            get {
                return ResourceManager.GetString("Generator_BG8502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidating &apos;{0}&apos; and all its nested types because some of its methods were invalid..
        /// </summary>
        public static string Generator_BG8503 {
            get {
                return ResourceManager.GetString("Generator_BG8503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name for &apos;{0}.{1}&apos; is invalid. A valid &apos;eventName&apos; or &apos;argsType&apos; can be assigned by adding a rule to the Metadata.xml transforms file..
        /// </summary>
        public static string Generator_BG8504 {
            get {
                return ResourceManager.GetString("Generator_BG8504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event property name for &apos;{0}.{1}&apos; is invalid. A valid &apos;eventName&apos; or &apos;argsType&apos; can be assigned by adding a rule to the Metadata.xml transforms file..
        /// </summary>
        public static string Generator_BG8506 {
            get {
                return ResourceManager.GetString("Generator_BG8506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XML file &apos;{0}&apos;: {1}..
        /// </summary>
        public static string Generator_BG8600 {
            get {
                return ResourceManager.GetString("Generator_BG8600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &apos;&lt;package&gt;&apos; elements found..
        /// </summary>
        public static string Generator_BG8601 {
            get {
                return ResourceManager.GetString("Generator_BG8601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected root child node: &apos;&lt;{0}&gt;&apos;..
        /// </summary>
        public static string Generator_BG8602 {
            get {
                return ResourceManager.GetString("Generator_BG8602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected &apos;&lt;package&gt;&apos; child node: &apos;&lt;{0}&gt;&apos;..
        /// </summary>
        public static string Generator_BG8603 {
            get {
                return ResourceManager.GetString("Generator_BG8603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find top ancestor type &apos;{0}&apos; for nested type &apos;{1}&apos;..
        /// </summary>
        public static string Generator_BG8604 {
            get {
                return ResourceManager.GetString("Generator_BG8604", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown return type &apos;{0}&apos; for member &apos;{1}&apos;..
        /// </summary>
        public static string Generator_BG8700 {
            get {
                return ResourceManager.GetString("Generator_BG8700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid return type &apos;{0}&apos; for member &apos;{1}&apos;..
        /// </summary>
        public static string Generator_BG8701 {
            get {
                return ResourceManager.GetString("Generator_BG8701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parameter type &apos;{0}&apos; for member &apos;{1}&apos;..
        /// </summary>
        public static string Generator_BG8800 {
            get {
                return ResourceManager.GetString("Generator_BG8800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter type &apos;{0}&apos; for member &apos;{1}&apos;..
        /// </summary>
        public static string Generator_BG8801 {
            get {
                return ResourceManager.GetString("Generator_BG8801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.xml element &apos;{0}&apos; matched no nodes..
        /// </summary>
        public static string Generator_BG8A00 {
            get {
                return ResourceManager.GetString("Generator_BG8A00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown generic argument constraint type &apos;{0}&apos; for member &apos;{1}&apos;..
        /// </summary>
        public static string Generator_BG8B00 {
            get {
                return ResourceManager.GetString("Generator_BG8B00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find base interface &apos;{1}&apos; for type &apos;{0}&apos;..
        /// </summary>
        public static string Generator_BG8C00 {
            get {
                return ResourceManager.GetString("Generator_BG8C00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For type &apos;{0}&apos;, base interface &apos;{1}&apos; is invalid..
        /// </summary>
        public static string Generator_BG8C01 {
            get {
                return ResourceManager.GetString("Generator_BG8C01", resourceCulture);
            }
        }
    }
}
